<template>
      <div v-if="loading" class="loading">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="44px" height="44px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="84" cy="50" r="10" fill="#e15b64">
    <animate attributeName="r" repeatCount="indefinite" dur="0.25s" calcMode="spline" keyTimes="0;1" values="10;0" keySplines="0 0.5 0.5 1" begin="0s"></animate>
    <animate attributeName="fill" repeatCount="indefinite" dur="1s" calcMode="discrete" keyTimes="0;0.25;0.5;0.75;1" values="#e15b64;#abbd81;#f8b26a;#f47e60;#e15b64" begin="0s"></animate>
</circle><circle cx="16" cy="50" r="10" fill="#e15b64">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"></animate>
</circle><circle cx="50" cy="50" r="10" fill="#f47e60">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.25s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.25s"></animate>
</circle><circle cx="84" cy="50" r="10" fill="#f8b26a">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"></animate>
</circle><circle cx="16" cy="50" r="10" fill="#abbd81">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.75s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.75s"></animate>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg>
    </div>
  <div class="container" v-else>
      <div class="box__left" v-if="images.length != 0">
              <div class="box__left-slider">
                  <div class="box__left-slider-img">
                    <img :src="currentImg" alt="image-slider">
                  </div>
              <div class="box__left-slider-leftarrow" v-on:click="prev" v-if="images.length > 2"><i class="fa-solid fa-chevron-left"></i></div>
              <div class="box__left-slider-rightarrow" v-on:click="next" v-if="images.length > 2"><i class="fa-solid fa-chevron-right"></i></div>
              <div class="box__left-slider-paginations" v-if="images.length > 2">
                  <span v-for="(element , index) in images" :key="index" :class="{active:currentIndex===index}" v-on:click="jump(index)"></span>
              </div>
          </div>
      </div>
      <div class="box__right" :class="{fullscreen:images.length == 0}">
          <div class="box__right-title">
              <h1>{{ data.widgets.header.title }}</h1>
          </div>
          <div class="box__right-time">{{ data.widgets.header.subtitle }}</div>
          <div class="box__right-call">
              <button v-on:click="isPhone = !isPhone">اطلاعات تماس</button>
              <p v-if="isPhone">{{ data.widgets.contact.phone }}</p>
          </div>
          <div class="box__right-price" v-if="data.data.webengage.price"><p><span>ریال</span> <span style="visibility: hidden;font-size:0rem;">i</span>{{ data.data.webengage.price.toLocaleString()}}</p><p>قیمت</p></div>
          <div class="box__right-desc">
              <p>توضیحات</p>
              <p>{{ data.widgets.description }}</p>
              </div>
      </div>
  </div>
</template>

<script>
export default {
    name: 'TizerPage' ,
    data(){
        return{
            images: '' ,
            currentIndex: 0 ,
            loading: true , 
            data: '' , 
            isPhone: false
        }
    } ,
    methods:{
        next(){
            console.log('object');
            this.currentIndex++;
            if(this.currentIndex > this.images.length - 1){
                this.currentIndex = 0;
            }
        } , 
        prev(){
            this.currentIndex--;
            if(this.currentIndex < 0){
                this.currentIndex = this.images.length - 1;
            }
        },
        jump(index){
            this.currentIndex = index;
        }
    } ,
    computed:{
        currentImg(){
            return this.images[this.currentIndex]
        }
    } ,
    fetch(){
        console.log('fetch');
        this.$axios.
        get(`https://one-api.ir/divar/?token=343050:60d87b72a4b9e8.68277188&action=post&id=${this.$route.params.id}`)
        .then((data)=>{
            this.loading = false;
            this.images = data.data.result.widgets.images; 
            this.data = data.data.result;
            console.log(data.data.result);
        })
        .catch((e)=>{
            console.log(e);
        })
    } , 
}
</script>

<style lang="scss" scoped>
@import './assets/color/color.scss';
.container{
    width: 80%;
    height: auto;
    margin: auto;
        display: flex;
        justify-content: space-between;
    .box__right{
        width: 50%;
        padding: 1rem;
        height: 100%;
        &-title , &-time , &-call , &-price , &-desc{
            width: 80%;
            padding: 1rem;
            margin: 10px auto;
            text-align: right;
            border-bottom: 1px solid $border-color;
        }
        &-title{
            font-size: 0.5rem;
        }
        &-time{
            color: $font-color-titr;
        }
        &-call{
            button{
                padding: 0.5rem 1.5rem;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                border: none;
                background: #BE3737;
            }
            p{
                padding: 1rem;
            }
        }
        &-desc p:nth-child(2){
            padding: 1rem 0;
            direction: rtl;
        }
        &-price{
            display: flex;
            p:nth-child(1){
               width: 50%;
               text-align: left; 
            }
            p:nth-child(2){
               width: 50%;
               text-align: right; 
            }
        }
    }
    .box__left{
        width: 50%;
        padding: 1rem;
        &-slider{
            width: 100%;
            height: 85vh;
            position: relative;
            &-rightarrow{
            width: 5%;
            text-align: center;
            position: absolute;
            background: rgba(156, 156, 156, 0.829);
                top: 50%;
                right: 0;
                color: white;
                transition: 250ms;
                cursor: pointer;
                &:hover{
                    transform: scale(1.5);
                    background: transparent;
                }
        }
        &-leftarrow{
            width: 5%;
            text-align: center;
            position: absolute;
            background: rgba(156, 156, 156, 0.829);
                top: 50%;
                left: 0;
                color: white;
                transition: 250ms;
                cursor: pointer;
                &:hover{
                    transform: scale(1.5);
                    background: transparent;
                }
        }
        &-img{
            width: 100%;
            height: 85vh;
            z-index: 1;
            img{
                width: 100%;
                height: 100%;
                border-radius: 5px;
            }
        }
        &-paginations{
            width: 100%;
            z-index: 2;
            text-align: center;
            position: absolute;
            bottom: 0px;
            cursor: pointer;
            span{
                width: 2%;
                height: 1vh;
                padding: 0.1rem;
                display: inline-block;
                border-radius: 50%;
                margin-right: 0.5rem;
                background: white;
            }
        }
        .active{
        background: rgba(255, 53, 53, 0.548);
        transform: scale(1.2);
    }
        }
    }
    .fullscreen{
        width: 100%;
    }
    .loading{
            width: 100%;
            text-align: center;
            margin: auto;
          }
}
</style>