<template>
<main class="main">
  <Error  v-if="showError"></Error>
<section class="main__left" v-else>
  <section class="main__left-top">
    <p>دیوار {{cityfa}} :‌ انواع آگهی‌ها و خدمات در {{cityfa}}</p>
  </section>
  <section class="main__left-center">
    <Card :item="item" v-for="item in items" :key="item.id"></Card>
  </section>
  <div v-if="loading" class="main__left-center-loading">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="44px" height="44px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="84" cy="50" r="10" fill="#e15b64">
    <animate attributeName="r" repeatCount="indefinite" dur="0.25s" calcMode="spline" keyTimes="0;1" values="10;0" keySplines="0 0.5 0.5 1" begin="0s"></animate>
    <animate attributeName="fill" repeatCount="indefinite" dur="1s" calcMode="discrete" keyTimes="0;0.25;0.5;0.75;1" values="#e15b64;#abbd81;#f8b26a;#f47e60;#e15b64" begin="0s"></animate>
</circle><circle cx="16" cy="50" r="10" fill="#e15b64">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"></animate>
</circle><circle cx="50" cy="50" r="10" fill="#f47e60">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.25s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.25s"></animate>
</circle><circle cx="84" cy="50" r="10" fill="#f8b26a">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"></animate>
</circle><circle cx="16" cy="50" r="10" fill="#abbd81">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.75s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.75s"></animate>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg>
    </div>
</section>
<section class="main__sidbar">
  <div class="main__sidbar-grouping">
    <ul v-on:click="showgrouping($event)">
      <li>دسته ها</li>
      <li>املاک <i class="fa-solid fa-house-chimney"></i></li>
      <li>وسایل نقلیه <i class="fa-solid fa-van-shuttle"></i></li>
      <li>موبایل <i class="fa-solid fa-mobile-button"></i></li>
      <li>خانه و آشپزخانه <i class="fa-solid fa-utensils"></i></li>
      <li>خدمات <i class="fa-solid fa-brush"></i></li>
      <li>وسایل شخصی <i class="fa-solid fa-user-tie"></i></li>
      <li>سرگرمی و فراغت <i class="fa-solid fa-dice"></i></li>
      <li>اجتماعی <i class="fa-solid fa-user-group"></i></li>
      <li>تجهیزات و صنعتی <i class="fa-solid fa-charging-station"></i></li>
      <li>استخدام و کاریابی <i class="fa-solid fa-bag-shopping"></i></li>
    </ul>
  </div>
  <div class="main__sidbar-location">
    <p>محل <i class="fa-solid fa-angle-down"></i></p>
  </div>
  <div class="main__sidbar-price">
    <p>قیمت <i class="fa-solid fa-angle-down"></i></p>
  </div>
  <div class="main__sidbar-condition">
    <p>وضعیت آگهی <i class="fa-solid fa-angle-down"></i></p>
  </div>
  <div class="main__sidbar-divar">
    <div class="main__sidbar-divar-blog">
      بلاگ دیوار
    </div>
    <div class="main__sidbar-divar-install">
      دریافت دیوار
    </div>
    <div class="main__sidbar-divar-about">
      درباره دیوار
    </div>
  </div>
  <div class="main__sidbar-social">
    <div class="main__sidbar-social-insta"><i class="fa-brands fa-instagram"></i></div>
    <div class="main__sidbar-social-twiter"><i class="fa-brands fa-twitter"></i></div>
    <div class="main__sidbar-social-linkdin"><i class="fa-brands fa-linkedin"></i></div>
  </div>
  <div class="main__sidbar-validation">
    <div class="main__sidbar-validation-box">
      <img src="../assets/img/vadidate.png" alt="validate">
    </div>
  </div>
  <br><br><br>
</section>
</main>
</template>

<script>
export default {
  name: 'HomePage',
  data(){
    return{
      showError: false ,
      items:[] ,
      number: 1,
      query: '' ,
      loading: true ,
      cityen: localStorage.getItem('cityen')?localStorage.getItem('cityen'):'tehran' ,
      cityfa: localStorage.getItem('cityfa')?localStorage.getItem('cityfa'):'تهران'
    }
  } ,
  methods:{
    showItems(){
        if(document.documentElement.scrollTop + document.documentElement.clientHeight >= document.documentElement.scrollHeight){
            this.number++;
            this.loading = true;
            this.$axios.
    get(`https://one-api.ir/divar/?token=343050:60d87b72a4b9e8.68277188&action=search&city=${this.cityen}&q=${this.query}&page=${this.number}`)
    .then((data)=>{
      this.items.push(...data.data.result);
      this.loading = false;
    })
      };
    } , 
    reset(){
      setTimeout(() => {
          this.showError = false;
          localStorage.clear();
          window.location.reload();
        }, 3000);
    } , 
    showgrouping(e){
      this.query = e.target.textContent;
      this.loading = true;
      const li = document.querySelectorAll('.main__sidbar-grouping ul li');
      for (const element of li) {
          element.classList.remove('active');
      }
      e.target.classList.add('active');
      this.$axios.
    get(`https://one-api.ir/divar/?token=343050:60d87b72a4b9e8.68277188&action=search&city=${this.cityen}&q=${this.query}&page=1`)
    .then((data)=>{
      if(data.data.status === 200){
        this.items = data.data.result;
        this.loading = false;
        window.scrollTo({
          top:0 , 
          behavior: 'smooth'
        })
      }
      else if(data.data.status === 500){
        this.loading = false;
        this.showError = true;
        this.reset();
      }
    })
    }
  } , 
  mounted(){
    window.addEventListener('scroll' , this.showItems);
  } ,
  fetch(){
    this.$axios.
    get(`https://one-api.ir/divar/?token=343050:60d87b72a4b9e8.68277188&action=search&city=${this.cityen}&q=${this.query}&page=1`)
    .then((data)=>{
      if(data.data.status === 200){
        this.items.push(...data.data.result);
        this.loading = false;
      }
      else if(data.data.status === 500){
        this.loading = false;
        this.showError = true;
        this.reset();
      }
    })
  }
}
</script>
<style lang="scss" scoped>
@import '@/assets/color/color.scss';
    .main{
      width: 100%;
      &__left{
        width: 80%;
        &-top{
          width: 95%;
          margin: auto;
          p{
            padding: 2rem 0 0.5rem;
            font-size: 0.8rem;
            color: $font-color;
          }
        }
        &-center{
          width: 95%;
          margin: auto;
          display: grid;
          grid-template-columns: repeat(3 , 1fr);
          grid-gap: 1rem;
          &-loading{
            width: 100%;
            text-align: center;
            margin: auto;
          }
        }
      }
      &__sidbar{
        width: 20%;
        position: fixed;
        right: 0;
        top: 10%;
        height: 100vh;
        overflow-y: scroll;
        &::-webkit-scrollbar{
          display: none;
        }
        &-grouping{
          font-size: 0.8rem;
          color: $font-color-titr;
          text-align: right;
          ul{
            padding: 2rem 1rem 0 1rem;
            list-style-type: none;
            li:not(:nth-child(1)){
              padding: 0.3rem 0;
              font-size: 0.9rem;
              color: $font-color;
            }
            li{
              padding: 0.5rem 0;
              color: $font-color-titr;
              cursor: pointer;
              transition: 250ms;
              &:hover{
              color: $font-color-titr;
          }
            }
            li:last-child{
              padding-bottom: 1rem;
              border-bottom: 1px solid $border-color;
            }
          }
        }
        &-location , &-price , &-condition{
          padding: 0 1rem;
          p{
          text-align: right;
          padding: 1rem 0;
          font-size: 0.8rem;
          border-bottom: 1px solid $border-color;
          }
          i{
            color: $font-color-titr;
            font-size: 0.8rem;
            padding-left: 0.5rem;
          }
        }
        &-divar{
          display: flex;
          justify-content: space-around;
          padding: 0 1rem;
          font-size: 0.7rem;
          color: $font-color;
          &-blog , &-install , &-about{
            cursor: pointer;
            padding: 1rem 0;
            transition: 1s;
            &:hover{
            color: $font-color-titr;
          }
          }
        }
        &-social{
          display: flex;
          justify-content: space-around;
          padding: 1rem;
          color: $font-color;
          i{
            transition: 1s;
            cursor: pointer;
          &:hover{
            color: $font-color-titr;
          }
          }
        }
        &-validation{
          display: flex;
          justify-content: space-between;
          cursor: pointer;
        }
        .active{
          color: red!important;
          }
      }
    }
</style>
